version: '3.9'

services:
  db:
    image: postgres:14.6
    restart: always
    container_name: senaiTest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: senaiTest
